// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqexulgmmtghwtgnqtfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxZXh1bGdtbXRnaHd0Z25xdGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwMzg1NzksImV4cCI6MjA3NTYxNDU3OX0.7G8MdMj2lSj8Ov9bacg6GkaLpMMiNFXAPceIbH8uVXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});